### PR TITLE
Adding documentation for CAPC

### PR DESCRIPTION
**Pull request by rohityadavcloud**

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
@davidjumani can you add in a link and move to primers - https://github.com/shapeblue/hackerbook/blob/main/primer/index.md

Also update the document as necessary. It must have these:
- Basic information or links to know about CAPI, CAPC
- How to build CAPC, test, debug and troubleshoot
- An exercise to do (implement a small feature, a fictitious task or a bugfix etc will sole purpose of learning it)

**Comment by rohityadavcloud** [comment]
ping @davidjumani

**Comment by rohityadavcloud** [comment]
@davidjumani could you the following:
- move this to the primer's folder
- add a link to this in the primer/index.md

**Comment by davidjumani** [comment]
Done @rohityadavcloud

**Comment by rohityadavcloud** [comment]
Merged, thnx @davidjumani

**Pull request merged**
